/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Sanon
 */
public class Dialog extends java.awt.Dialog {
//Main_View v=new Main_View()
    /**
     * Creates new form Dialog
     */
    
    public Dialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setLocation(440, 200);
        this.setTitle("Enregistrer");
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        chooser = new javax.swing.JFileChooser();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        chooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooserActionPerformed(evt);
            }
        });
        add(chooser, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    
    
    public String ouvrir(){
        JTextArea text=new JTextArea();
         FileNameExtensionFilter filter = new FileNameExtensionFilter (
         "java", "java");
         chooser.setFileFilter(filter);
         
        int ret=chooser.showOpenDialog(text);
        String path="";
        if(ret==JFileChooser.APPROVE_OPTION){
            path=chooser.getSelectedFile().getAbsolutePath();
            }

        return path;
        }
    
    
       public String enr(){
           chooser.setName("Enregistrer");
             FileNameExtensionFilter filter = new FileNameExtensionFilter (
         "java", "java");
         chooser.setFileFilter(filter);
         
        int ret=chooser.showSaveDialog(this);
        //if(ret==chooser){}
        String path="";
        
        if(ret==JFileChooser.APPROVE_OPTION){
            path=chooser.getSelectedFile().getAbsolutePath();
            File f=new File(path);
            String n=f.getName();
            if(!n.endsWith(".java")){
                f=new File(n+".java");
                path=f.getAbsolutePath();
            }
            }
            
        return path;
         
        }
      

      public String ouvrir1(){
          
        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int ret=chooser.showOpenDialog(this);
        String nom="";
         
        if(ret==JFileChooser.FILES_AND_DIRECTORIES){
            
            nom=chooser.getSelectedFile().getAbsolutePath();
           
           //nom1=nom.substring(0, nom.lastIndexOf("" ));
           
            }

        return nom;
        }  
    

    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void chooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooserActionPerformed

        ouvrir();
        this.dispose();
    }//GEN-LAST:event_chooserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dialog dialog = new Dialog(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser chooser;
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
}
